//
//  Events.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class Events: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _articleId: String?
    var _category: String?
    var _content: String?
    var _creationDate: NSNumber?
    var _title: String?
    var _venueInfo: Set<String>?
    var _venueName: String?
    
    class func dynamoDBTableName() -> String {

        return "projectsupreme-mobilehub-1395306802-Events"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_articleId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_articleId" : "articleId",
               "_category" : "category",
               "_content" : "content",
               "_creationDate" : "creationDate",
               "_title" : "title",
               "_venueInfo" : "venueInfo",
               "_venueName" : "venueName",
        ]
    }
}
